name: hawk
on:
  push:
    branches:
      - roblox
    paths:
      - '/scripts/CoreScripts/Modules/BackpackScript.lua'

jobs:
  hawk:
    name: hawk
    runs-on: ubuntu-latest
    
    steps:
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: ${{ secrets.SECRET_WEBHOOK }}
        slack_message: 'Contents of some important file were changed on roblox'
