name: hawk
on:
  push:
    branches:
      - roblox
    paths:
      - '/scripts/CoreScripts/Modules/BackpackScript.lua'

jobs:
  hawk:
    name: hawk
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print debug info
      run: |
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        echo "Path: /scripts/CoreScripts/Modules/BackpackScript.lua"
    
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: ${{ secrets.SECRET_WEBHOOK }}
        slack_message: 'Contents of some important file were changed on roblox'
